export const ERROR_CODES = {
    ERR_INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
    ERR_INVALID_INPUT: 'ERR_INVALID_INPUT',
    ERR_NOT_FOUND: 'ERR_NOT_FOUND',
    ERR_UNPROCESSABLE_ENTITY: 'ERR_UNPROCESSABLE_ENTITY',
    ERR_BAD_REQUEST: 'ERR_BAD_REQUEST',
    SUCCESS: 'SUCCESS',
};

export const ERROR_MESSAGES = {
    ERR_INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
    ERR_INVALID_INPUT: 'ERR_INVALID_INPUT',
    ERR_NOT_FOUND: 'ERR_NOT_FOUND',
    ERR_UNPROCESSABLE_ENTITY: 'ERR_UNPROCESSABLE_ENTITY',
    ERR_BAD_REQUEST: 'ERR_BAD_REQUEST',
    SUCCESS: 'SUCCESS'
};

export default {
    ERROR_CODES,
    ERROR_MESSAGES,
};
