export const ERROR_CODES = {
    ERR_INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
    ERR_INVALID_INPUT: 'ERR_INVALID_INPUT',
    ERR_USER_ALREADY_EXISTS: 'ERR_USER_ALREADY_EXISTS',
    SUCCESS: 'SUCCESS',
};

export const ERROR_MESSAGES = {
    ERR_INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
    USER_ALREADY_EXISTS: 'Email Id already exists',
};

export default {
    ERROR_CODES,
    ERROR_MESSAGES,
};
